// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addAluno": {
            "post": {
                "description": "Adiciona um aluno",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addAluno"
                ],
                "summary": "Adiciona um aluno",
                "parameters": [
                    {
                        "description": "Aluno",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Aluno"
                            }
                        }
                    }
                }
            }
        },
        "/addAtividade": {
            "post": {
                "description": "Adiciona uma atividade",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addAtividade"
                ],
                "summary": "Adiciona uma atividade",
                "parameters": [
                    {
                        "description": "Atividade",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Atividade"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Atividade"
                            }
                        }
                    }
                }
            }
        },
        "/addEntrega": {
            "post": {
                "description": "Adiciona uma entrega",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addEntrega"
                ],
                "summary": "Adiciona uma entrega",
                "parameters": [
                    {
                        "description": "Entrega",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Entrega"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Entrega"
                            }
                        }
                    }
                }
            }
        },
        "/addProfessor": {
            "post": {
                "description": "Adiciona um professor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addProfessor"
                ],
                "summary": "Adiciona um professor",
                "parameters": [
                    {
                        "description": "Professor",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Professor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Professor"
                            }
                        }
                    }
                }
            }
        },
        "/aluno/{id}": {
            "get": {
                "description": "Pega um aluno",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getAluno"
                ],
                "summary": "Pega um aluno",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Aluno"
                            }
                        }
                    }
                }
            }
        },
        "/alunos": {
            "get": {
                "description": "Pega todos os alunos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getAlunos"
                ],
                "summary": "Pega todos os alunos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Aluno"
                            }
                        }
                    }
                }
            }
        },
        "/atividade/{id}": {
            "get": {
                "description": "Pega uma atividade",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getAtividade"
                ],
                "summary": "Pega uma atividade",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Atividade"
                            }
                        }
                    }
                }
            }
        },
        "/atividades": {
            "get": {
                "description": "Pega tados as atividades",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getAtividades"
                ],
                "summary": "Pega tados as atividades",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Atividade"
                            }
                        }
                    }
                }
            }
        },
        "/entrega/{id}": {
            "get": {
                "description": "Pega uma entrega",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getEntrega"
                ],
                "summary": "Pega uma entrega",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Entrega"
                            }
                        }
                    }
                }
            }
        },
        "/entregas": {
            "get": {
                "description": "Pega todas as entregas",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getEntregas"
                ],
                "summary": "Pega todas as entregas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Entrega"
                            }
                        }
                    }
                }
            }
        },
        "/professor/{id}": {
            "get": {
                "description": "Pega um professor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getProfessor"
                ],
                "summary": "Pega um professor",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Professor"
                            }
                        }
                    }
                }
            }
        },
        "/professores": {
            "get": {
                "description": "Pega todos os professores",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "getProfessores"
                ],
                "summary": "Pega todos os professores",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Professor"
                            }
                        }
                    }
                }
            }
        },
        "/updateEntrega": {
            "put": {
                "description": "Atualiza a nota na entrega do aluno",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "updateEntrega"
                ],
                "summary": "Atualiza a nota na entrega do aluno",
                "parameters": [
                    {
                        "description": "EntregaRequest",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EntregaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.EntregaRequest"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Aluno": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "models.Atividade": {
            "type": "object",
            "properties": {
                "data_entrega": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "professor_id": {
                    "type": "integer"
                },
                "titulo": {
                    "type": "string"
                }
            }
        },
        "models.Entrega": {
            "type": "object",
            "properties": {
                "aluno_id": {
                    "type": "integer"
                },
                "atividade_id": {
                    "type": "integer"
                },
                "disciplina": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nota": {
                    "type": "string"
                }
            }
        },
        "models.EntregaRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nota": {
                    "type": "string"
                }
            }
        },
        "models.Professor": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Gerenciador de Atividades API",
	Description:      "This is an example API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
